FROM python:3

RUN apt-get update && apt-get -y install \
    libpq-dev

WORKDIR /boxinity-django
ADD    ./boxinity   /boxinity-django/
RUN    pip install -r requirements.txt

EXPOSE 8000
CMD ["./init.sh"]

